### ISSUE TITLE
Filter by Tag value

### ISSUE THREAD

**Issue by jangrewe** [keegancsmith/prometheus-ec2-discovery#1]
Would it be possible to filter the EC2 instances that are being wrote to the config, e.g. only include those instances that have a tag like "Service=ecs"? 
Right now i'm seeing a lot of targets that are not supposed to be monitored, and i'd like to exclude them from the config.

Thanks! =)

**Comment by keegancsmith** [comment]
Great idea, check out the latest master for the implementation. Thanks!

**Comment by jangrewe** [comment]
Thanks for adding this, but "unfortunately" i discovered that Prometheus also provides Service Discovery via Consul, and i switched to that now, so i can't test it anymore... sorry for asking for this feature and now not needing it =(

**Comment by keegancsmith** [comment]
haha no worries. Consul is def a better place to get the information from.
I've infact switched to using it as well.
